name: PR Link Checker

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  pr-link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Check PR link
        run: |
          PR_DESCRIPTION=$(curl -sSL ${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ github.event.number }} | jq -r '.body')
          LINK=$(echo "$PR_DESCRIPTION" | grep -oP 'https?://\S+')
          echo "$LINK"

          if [ -n "$LINK" ]; then
            RESPONSE=$(curl -sL "$LINK")

            # Check for phrases in the response
            if echo "$RESPONSE" | grep -q "Produced\|Phrase2\|Phrase3"; then
              echo "PR cannot be merged. Found one of the prohibited phrases."
              exit 1
            else
              echo "No prohibited phrases found. PR can be merged."
            fi
          else
            echo "No link found in the PR description. Proceeding with the merge."
          fi
